//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class banner
    {
        public string ma_banner { get; set; }
        public string ten_banner { get; set; }
        public string mo_ta { get; set; }
        public string link { get; set; }
        public string image { get; set; }
        public string isSlide { get; set; }
    }
}
