//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctdonhang
    {
        public string ma_don_hang { get; set; }
        public string ma_hang { get; set; }
        public Nullable<int> so_luong { get; set; }
        public Nullable<int> thanh_tien { get; set; }
    
        public virtual donhang donhang { get; set; }
        public virtual hang hang { get; set; }
    }
}
