//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class donhang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public donhang()
        {
            this.ctdonhangs = new HashSet<ctdonhang>();
        }
    
        public string ma_don_hang { get; set; }
        public string username { get; set; }
        public string dia_chi { get; set; }
        public Nullable<int> thanhtien { get; set; }
        public Nullable<int> tinhtrangthanhtoan { get; set; }
        public string hoten_dh { get; set; }
        public string sdt_dh { get; set; }
        public Nullable<System.DateTime> ngay_thanh_toan { get; set; }
        public string email_dh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctdonhang> ctdonhangs { get; set; }
        public virtual taikhoan taikhoan { get; set; }
    }
}
