//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class hang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hang()
        {
            this.ctdonhangs = new HashSet<ctdonhang>();
            this.hinh_anh_mo_ta = new HashSet<hinh_anh_mo_ta>();
        }
    
        public string ma_hang { get; set; }
        public string ten_hang { get; set; }
        public Nullable<int> gia_cu { get; set; }
        public Nullable<int> gia_moi { get; set; }
        public string thuong_hieu { get; set; }
        public string hinh_dai_dien { get; set; }
        public Nullable<int> trang_thai { get; set; }
        public string mo_ta { get; set; }
        public string ma_loai { get; set; }
    
        public virtual ct_the_loai ct_the_loai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctdonhang> ctdonhangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hinh_anh_mo_ta> hinh_anh_mo_ta { get; set; }
    }
}
