//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class hinh_anh_mo_ta
    {
        public string ma_danh_sach_anh { get; set; }
        public string ma_hang { get; set; }
        public string hinh_dai_dien { get; set; }
    
        public virtual hang hang { get; set; }
    }
}
